# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62cec27685cb669902f1f7e99b37e4aed75c4bca09c29e7fd10eacf913aedce5aa4bcccd3f831a612cc2c680f26acb36356b0570e220e1193ca02b671a19e270

test:
  secret_key_base: fdddd8da6c975cb86cd3d11cd48c0e71a017f2e104262cd7a6d7ad597bb372bf3469ee97ada892329559ac5ba549f2ed66db072ca785c05e110c80170c58f341

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
